# Generated by Django 5.0.3 on 2024-03-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_owner_name', models.CharField(max_length=20)),
                ('flat_price', models.IntegerField()),
                ('flat_no', models.IntegerField()),
                ('maintaince_price', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('ON', 'ONLINE PAYMENT'), ('EMI', 'MONTHLY INSTALLMENT')], max_length=10)),
                ('room_quantity', models.CharField(choices=[('1BHK', '1bed room'), ('2BHK', '2bed room'), ('3BHK', '3bed room')], max_length=10)),
            ],
        ),
    ]
